#!/usr/bin/env python3
"""Driver for one bounded WaveKit software capacity run (host side, Docker).

It starts two throwaway containers on a private network: a SYNTHETIC rtl_tcp
server (fake_rtl_tcp.py) and a WaveKit container built from --image. Both get
distinct names (wkcap-*). No host ports are published, and running
deployments, compose projects and image tags are never touched. The WaveKit
container gets a hard memory cap (--memory equal to --memory-swap, so it
cannot swap) and a CPU quota. If its usage hits the cap, the OOM killer works
inside that cgroup and other containers are unaffected.

Safety: before starting, and every --guard seconds while running, the driver
reads VM MemAvailable. It aborts the run (removing its own containers only) if
MemAvailable is below --min-available-mib. It also records `docker stats` for
the --protect container, which defaults to the live wavekit-app. Preflight
refuses to start while that container uses more than --max-protect-cpu
(default 5%) unless --allow-live is given. A run is marked aborted if the
synthetic source logs a client disconnect inside the measurement window.

All output goes to --out (e.g. output/capacity/<run-id>/, gitignored):
config.yaml, meta.json, samples.jsonl (from sampler.py), app.log, fake.log
and guard.jsonl. Use summarize.py to reduce them.

This measures software delivery capacity on this host only. It is not RF
decode correctness or Pi/streaming stability.
"""

import argparse
import datetime
import json
import os
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ALL_DECODERS = [
    ("dsd-fme", "dsd-fme", {"mode": "auto", "output": "null"}),
    ("multimon-ng", "multimon-ng", {"modes": ["POCSAG512", "POCSAG1200", "POCSAG2400", "FLEX",
                                              "EAS", "AFSK1200", "FSK9600", "DTMF"]}),
    ("rtl433", "rtl433", {}),
    ("readsb", "readsb", {"outputFormat": "sbs", "outputPort": 30003}),
    ("acarsdec", "acarsdec", {}),
    ("ais-catcher", "ais-catcher", {}),
    ("dumpvdl2", "dumpvdl2", {"frequencies": [136975000], "followCenter": True}),
    ("direwolf", "direwolf", {}),
    ("lora-meshtastic", "lora-meshtastic", {"region": "EU_868", "preset": "LongFast",
                                            "frequency": 869525000, "channelKey": "AQ==",
                                            "followCenter": True}),
]


def docker(*args, check=True, capture=True):
    result = subprocess.run(["docker", *args], capture_output=capture, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"docker {' '.join(args[:3])}... failed: {result.stderr.strip()}")
    return result.stdout if capture else ""


def cpu_percent(stats):
    try:
        return float(str(stats.get("CPUPerc", "")).rstrip("%"))
    except ValueError:
        return None  # container absent: nothing to protect


def parse_events(text):
    events = []
    for line in text.splitlines():
        if line.startswith("{"):
            try:
                events.append(json.loads(line))
            except ValueError:
                pass
    return events


def cap_mib(value):
    units = {"k": 1 / 1024, "m": 1, "g": 1024}
    return int(float(value[:-1]) * units[value[-1].lower()]) if value[-1].isalpha() \
        else int(value) // 2**20


def vm_mem_available_mib(image):
    text = docker("run", "--rm", "--network", "none", "--entrypoint", "cat", image, "/proc/meminfo")
    for line in text.splitlines():
        if line.startswith("MemAvailable:"):
            return int(line.split()[1]) // 1024
    raise RuntimeError("MemAvailable not found")


def protect_stats(name):
    out = docker("stats", "--no-stream", "--format", "{{json .}}", name, check=False)
    try:
        row = json.loads(out.strip().splitlines()[0])
        return {k: row.get(k) for k in ("Name", "CPUPerc", "MemUsage", "MemPerc")}
    except (ValueError, IndexError):
        return {"error": out.strip()[:200]}


def write_config(path, rate, decoders, center):
    lines = [
        "# Generated by scripts/capacity/run_capacity.py - SYNTHETIC source",
        "sources:",
        "  - id: synth-iq",
        "    type: rtl_tcp",
        "    host: wkcap-fake",
        "    port: 1234",
        "    caps:",
        "      kind: iq",
        "      format: U8_IQ",
        f"      sampleRate: {rate}",
        f"      centerFreq: {center}",
        "      exclusive: false",
        "decoders:",
    ]
    for decoder_id, decoder_type, options in decoders:
        lines += [
            f"  - id: {decoder_id}",
            f"    type: {decoder_type}",
            "    enabled: true",
            "    sourceId: synth-iq",
            f"    options: {json.dumps(options)}",
        ]
    lines += [
        "api:", "  host: 0.0.0.0", "  port: 9000",
        "audio:", "  tcpPort: 8080", "  monitoring: false",
        "tunerRelay:", "  enabled: false",
        "liveDemod:", "  enabled: false",
        "resources:", "  containerMonitor:", "    enabled: true",
        "  sdrHostPoller:", "    enabled: false",
        "logging:", "  level: info",
    ]
    path.write_text("\n".join(lines) + "\n")


def wait_healthy(timeout):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        result = subprocess.run(
            ["docker", "exec", "wkcap-app", "curl", "-fsS", "http://127.0.0.1:9000/health"],
            capture_output=True, text=True)
        if result.returncode == 0:
            return True
        time.sleep(2)
    return False


def cleanup(network):
    for name in ("wkcap-app", "wkcap-fake"):
        subprocess.run(["docker", "rm", "-f", name], capture_output=True)
    subprocess.run(["docker", "network", "rm", network], capture_output=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", required=True)
    parser.add_argument("--rate", type=int, required=True)
    parser.add_argument("--buffers", choices=["on", "off"], required=True)
    parser.add_argument("--decoders", default="all", help="'all' or comma-separated ids")
    parser.add_argument("--warmup", type=float, default=30)
    parser.add_argument("--window", type=float, default=180)
    parser.add_argument("--interval", type=float, default=5)
    parser.add_argument("--memory", default="640m", help="hard cap, e.g. 640m or 1g")
    parser.add_argument("--cpus", default="4")
    parser.add_argument("--min-available-mib", type=int, default=1024)
    parser.add_argument("--guard", type=float, default=5)
    parser.add_argument("--protect", default="wavekit-app")
    parser.add_argument("--max-protect-cpu", type=float, default=5.0,
                        help="refuse to start if --protect uses more CPU %% than this")
    parser.add_argument("--allow-live", action="store_true",
                        help="run even while --protect is busy (results then contended)")
    parser.add_argument("--center", type=int, default=446524920)
    parser.add_argument("--out", required=True)
    options = parser.parse_args()
    assert options.warmup + options.window <= 300, "runs are bounded to 5 minutes"

    out = Path(options.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    network = "wkcap-net"
    decoders = ALL_DECODERS if options.decoders == "all" else [
        d for d in ALL_DECODERS if d[0] in options.decoders.split(",")]
    write_config(out / "config.yaml", options.rate, decoders, options.center)

    available = vm_mem_available_mib(options.image)
    meta = {
        "startedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "image": docker("image", "inspect", "--format", "{{.Id}}", options.image).strip(),
        "imageTag": options.image,
        "gitHead": subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True,
                                  cwd=HERE).stdout.strip(),
        "rate": options.rate, "buffers": options.buffers,
        "decoders": [d[0] for d in decoders], "warmup": options.warmup,
        "window": options.window, "interval": options.interval,
        "memoryCap": options.memory, "cpus": options.cpus, "source": "synthetic fake_rtl_tcp.py",
        "preflight": {"vmMemAvailableMiB": available, "protect": protect_stats(options.protect),
                      "hostLoadAvg": [round(x, 1) for x in os.getloadavg()]},
    }
    (out / "meta.json").write_text(json.dumps(meta, indent=2))
    # Even if both containers fill their caps, VM MemAvailable must stay above the floor.
    required = cap_mib(options.memory) + 128 + options.min_available_mib
    if available < required:
        print(f"ABORT preflight: VM MemAvailable {available} MiB < {required} MiB "
              f"(cap + fake source + floor)", file=sys.stderr)
        return 2
    protect_cpu = cpu_percent(meta["preflight"]["protect"])
    if protect_cpu is not None and protect_cpu > options.max_protect_cpu and not options.allow_live:
        print(f"ABORT preflight: {options.protect} is at {protect_cpu}% CPU (> "
              f"{options.max_protect_cpu}%); likely live streaming. Use --allow-live to "
              "override.", file=sys.stderr)
        return 2

    cleanup(network)
    docker("network", "create", network)
    aborted = None
    try:
        docker("run", "-d", "--name", "wkcap-fake", "--network", network,
               "--cpus", "1", "--memory", "128m", "--memory-swap", "128m",
               "--entrypoint", "python3", "-v", f"{HERE}:/capacity:ro", options.image,
               "/capacity/fake_rtl_tcp.py", "--rate", str(options.rate),
               "--duration", str(options.warmup + options.window + 90))
        bounded = "true" if options.buffers == "on" else "false"
        docker("run", "-d", "--name", "wkcap-app", "--network", network,
               "--cpus", options.cpus, "--memory", options.memory,
               "--memory-swap", options.memory,
               "-e", "WAVEKIT_CONFIG=/wkcap/config.yaml",
               "-e", f"WAVEKIT_CSDR__BOUNDED_BUFFERS={bounded}",
               "-e", "WAVEKIT_CSDR__BUFFER_ELEMENTS=65536",
               "-v", f"{out}:/wkcap", "-v", f"{HERE}:/capacity:ro", options.image)
        if not wait_healthy(90):
            aborted = "app not healthy within 90s"
            return 3
        time.sleep(options.warmup)
        docker("exec", "-d", "wkcap-app", "python3", "/capacity/sampler.py",
               "--out", "/wkcap/samples.jsonl", "--duration", str(options.window),
               "--interval", str(options.interval))
        start = time.monotonic()
        window_start_wall = time.time()
        with (out / "guard.jsonl").open("w") as guard:
            while time.monotonic() - start < options.window + 10:
                time.sleep(options.guard)
                vm = None
                samples = out / "samples.jsonl"
                if samples.exists():
                    lines = samples.read_text().splitlines()
                    if lines:
                        last = json.loads(lines[-1])
                        vm = (last.get("vmMemAvailableKiB") or 0) // 1024
                        if last.get("final"):
                            break
                row = {"t": round(time.monotonic() - start, 1), "vmMemAvailableMiB": vm,
                       "protect": protect_stats(options.protect)}
                guard.write(json.dumps(row) + "\n")
                guard.flush()
                if vm is not None and vm < options.min_available_mib:
                    aborted = f"VM MemAvailable {vm} MiB below {options.min_available_mib}"
                    break
        window_end_wall = time.time()
        fake_log = subprocess.run(["docker", "logs", "wkcap-fake"], capture_output=True,
                                  text=True).stdout
        drops = [e for e in parse_events(fake_log) if e.get("event") == "disconnected"
                 and window_start_wall <= e.get("ts", 0) <= window_end_wall]
        if drops and not aborted:
            aborted = f"source client disconnected {len(drops)}x inside the window"
        return 4 if aborted else 0
    finally:
        logs = subprocess.run(["docker", "logs", "wkcap-app"], capture_output=True, text=True)
        (out / "app.log").write_text(logs.stdout + logs.stderr)
        (out / "fake.log").write_text(
            subprocess.run(["docker", "logs", "wkcap-fake"], capture_output=True, text=True).stdout)
        meta["aborted"] = aborted
        meta["endHostLoadAvg"] = [round(x, 1) for x in os.getloadavg()]
        meta["endedAt"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
        (out / "meta.json").write_text(json.dumps(meta, indent=2))
        cleanup(network)
        if aborted:
            print(f"ABORTED: {aborted}", file=sys.stderr)


if __name__ == "__main__":
    sys.exit(main())
